INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1228,  'Категории товаров', null, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1343,  'Категории услуг', null, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1229,  'Автосервис/Автотовары', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1248,  'Медицина/Здоровье/Красота.', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6470,  'Оборудование/Инструмент', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6421,  'Продукты питания/Напитки', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6448,  'Одежда/Обувь', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6395,  'Электроника/Электротехника', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6413,  'Реклама/Полиграфия/СМИ', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6380,  'Спорт/Отдых/Туризм', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6388,  'Товары для животных /Ветеринария', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1319,  'Интерьер', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1307,  'Сельское хозяйство', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1303,  'Охрана/Безопасность', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1253,  'Металлы/Топливо/Химия', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1284,  'Мебель/Материалы/Фурнитура', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1244,  'Бытовая/Офисная/Цифровая техника/Техника для искусства', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1265,  'Хозтовары / Канцелярия / Упаковка', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1262,  'Строительство/Ремонт', 1228, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1239,  'Информационные технологии: Интернет/связь', 1228, 1227);



INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1376,  'Медицинские услуги', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1365,  'Коммуникационные и IT услуги', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1371,  'Техническая поддержка', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1344,  'Бизнес-услуги/Финансы/Право', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1380,  'Образование', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1391,  'Ремонт и обслуживание авто- и мототехники', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1414,  'Строительство', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1402,  'Реклама/Полиграфия/СМИ', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1396,  'Недвижимость/Земля', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1443,  'Туризм/Досуг/Общепит', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1387,  'Охрана/Безопасность', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1431,  'Транспорт/Грузоперевозки/Логистика', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1470,  'Прочие услуги', 1343, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1466,  'Красота/Здоровье', 1343, 1342);



INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1230,  'Автоаксессуары', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1237,  'АЗС', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1243,  'Программное обеспечение', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1249,  'Аптеки', 1248, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1233,  'Контрактные автозапчасти', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1234,  'Газовое оборудование для автотранспорта', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1232,  'Тюнинговые комплектующие', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1238,  'Автооборудование', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1231,  'Автозапчасти', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1241,  'Телефонная связь', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1240,  'Интернет оборудование(провайдеры)', 1239, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1242,  'Радиосвязь/оборудование', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1250,  'Парфюмерно-косметические торговые площади', 1248, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1251,  'Оптика', 1248, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1252,  'Расходные материалы', 1248, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1263,  'Строительные/Отделочные материалы', 1262, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1264,  'Системы водоотведения', 1262, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1254,  'Графитированное производство', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1255,  'Дезинфицирующие товары/оборудование', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1256,  'Металлоконструкции /Металлоизделия', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1257,  'Красящие вещества', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1259,  'Сварочные изделия', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1258,  'Литейное производство', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1260,  'Металлы/Сплавы', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1261,  'Нефтепродукты/ГАЗ/ГСМ', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1295,  'Детская мебель', 1284, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1266,  'Бытовая химия', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1267,  'Хозяйственные товары', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1269,  'Садово-огородный инвентарь / материал / техника', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1271,  'Книги / Учебная литература', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1270,  'Канцелярские товары / Учебные принадлежности', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1272,  'Блистерная упаковка', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1273,  'Бумажная упаковка', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1274,  'Деревянная тара', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1275,  'Подарочная упаковка', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1278,  'Одноразовая посуда', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1277,  'Металлическая / Жестяная тара', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1279,  'Гофротара', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1281,  'Стеклянная тара', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1296,  'Корпусная мебель', 1284, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1245,  'Бытовая техника', 1244, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1246,  'Офисная техника', 1244, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1297,  'Бескарская мебель', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1247,  'Цифровая техника \ Аксессуары', 1244, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1298,  'Мягкая мебель', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1299,  'Пластиковая мебель', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1285,  'Профильная мебель', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1292,  'для предприятий общественного питания', 1285, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1287,  'для медицинские учреждений', 1285, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1293,  'для учебных/дошкольных организаций', 1285, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1306,  'Системы безопасности и охраны', 1303, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1311,  'Зерно', 1307, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1345,  'Аудиторские услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1346,  'Адвокаты и адвокатские образования', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1347,  'Банковская деятельность', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1349,  'Бухгалтерские услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1351,  'Кадровые агентства', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1352,  'Коллекторские услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1353,  'Лизинговые услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1354,  'Саморегулируемые организации (СРО)', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1355,  'Нотариальные услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1356,  'Патентные услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1357,  'Регистрация ценных бумаг', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1358,  'Организация выставок', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1359,  'Оценка, экспертиза', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1360,  'Страхование', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1361,  'Специальная оценка условий труда', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1362,  'Таможенные услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1363,  'Финансовый консалтинг', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1364,  'Юридические услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1366,  'Автоматизация бизнес-процессов', 1365, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1367,  'Автоматизация производственных процессов', 1365, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1369,  'Информационная безопасность', 1365, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1372,  'Заправка картриджей', 1371, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1373,  'Ремонт оргтехники', 1371, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1374,  'Ремонт компьютеров', 1371, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1375,  'Услуги системного администрирования', 1371, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1309,  'Агрохимия/Агротовары', 1307, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1312,  'Корма/Комбикорма', 1307, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1310,  'Животноводство/Птицеводство', 1307, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1314,  'Продукция пчеловодства', 1307, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1313,  'Оборудование/Техника/Инструмент', 1307, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1317,  'Растениеводство/Семена/Корнеплоды/Удобрения', 1307, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1318,  'Тепличное хозяйство/Оборудование', 1307, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1304,  'Охранно-пожарные системы / оборудование', 1303, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1305,  'Спасательное оборудование / инструмент', 1303, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1300,  'Плетеная мебель', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1301,  'Металлическая мебель', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1302,  'Мебель из стекла', 1284, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1320,  'Домашний интерьер', 1319, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1331,  'Коммерческий интерьер', 1319, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1322,  'Жалюзи/ Рольставни', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1323,  'Интерьерные лестницы / ограждения', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1324,  'Керамические изделия', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1325,  'Нетканые материалы', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1326,  'Печи/ камины', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1327,  'Ткани / шторы / Пряжа', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1328,  'Текстиль', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1329,  'Ковры', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1333,  'Материалы', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1334,  'Мебель', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1335,  'Оборудование', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1336,  'Декор / Аксессуары', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1337,  'Текстиль', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1338,  'Архитектура / Оборудование / Материалы', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1339,  'Ландшафтный дизайн / Оборудование / Инструмент', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1340,  'Нетканые материалы', 1331, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1350,  'Архивные услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1370,  'Разработка, поддержка и продвижение Web-сайтов', 1365, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1368,  'Интернет/Телефония', 1365, 1342);


INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1377,  'Больницы и поликлиники', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1378,  'Медицинские центры', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1379,  'Услуги узких специалистов', 1376, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1381,  'Автошколы', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1382,  'Дополнительное образование', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1383,  'Курсы', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1384,  'Обучение за рубежом', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1385,  'Профессиональная переподготовка, повышение квалификации', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1386,  'Бизнес-тренинги, семинары', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1388,  'Монтаж охранно-пожарных систем', 1387, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1389,  'Услуги инкассации', 1387, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1390,  'Услуги охраны', 1387, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1392,  'Автомойки', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1394,  'Ремонт автоэлектрики', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1395,  'Ремонт и техобслуживание авто- и мототехники;', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1400,  'Управление недвижимым имуществом', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1405,  'Наружная реклама', 1402, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1408,  'Дизайн рекламы', 1402, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1411,  'Печати и штампы', 1402, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1417,  'Дизайн интерьеров, ландшафтный дизайн', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1418,  'Индивидуальное жилищное строительство', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1419,  'Монтаж инженерных систем и оборудования', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1420,  'Сантехнические работы', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1424,  'Строительство бань, саун', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1425,  'Промышленное строительство', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1426,  'Реконструкция и капремонт зданий', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1427,  'Ремонт, отделка помещений', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1428,  'Фасадные работы', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1429,  'Электромонтажные и электроизмерительные работы', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1430,  'Прочие услуги в сфере строительства и ремонта', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1432,  'Аренда и прокат транспорта', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1433,  'Автомобильные грузоперевозки', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1434,  'Ж/д грузоперевозки', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1436,  'Пассажирские авиаперевозки', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1437,  'Пассажирские автоперевозки', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1438,  'Пассажирские ж/д перевозки', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1440,  'Такси', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1441,  'Услуги складского хранения', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1442,  'Экспресс-доставка', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1444,  'Базы отдыха', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1404,  'Маркетинговые услуги', 1402, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1406,  'Реклама на транспорте', 1402, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1412,  'Рекламные и PR-агентства', 1402, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1409,  'Indoor - реклама', 1402, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1407,  'Интернет-реклама', 1402, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1410,  'Полиграфия/Услуги типографий', 1402, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1397,  'Агентства недвижимости/риэлторы', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1398,  'Аренда офисов/производственных/складских площадей', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1399,  'Аренда торговых площадей', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1401,  'Оценка, экспертиза объектов недвижимости', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1415,  'Аренда оборудования', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1416,  'Проектирование зданий и сооружений', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1421,  'Проектирование сетей и коммуникаций', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1422,  'Строительство многоэтажное', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1435,  'Морские/речные грузоперевозки', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1439,  'Пассажироперевозки морские/речные', 1431, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1446,  'Организация развлекательных и досуговых мероприятий', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1445,  'Гостиницы, отели, гостевые дома', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1447,  'Прокат инвентаря/техники', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1393,  'Автосигнализации/автозвук установка', 1391, 1342);


INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1423,  'Строительство специальных сооружений', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1448,  'Профессиональные спортивные клубы', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1449,  'Спортивно-интеллектуальные клубы', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1453,  'Бары, рестораны', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1454,  'Бильярд', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1455,  'Боулинг', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1456,  'Кафе', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1457,  'Кофейни', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1458,  'Караоке клубы', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1459,  'Кинотеатры', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1460,  'Музеи', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1461,  'Ночные клубы', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1463,  'Парки культуры и отдыха', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1464,  'Развлекательные комплексы', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1465,  'Театры', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1467,  'Салоны красоты', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1468,  'SPA-салоны', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1469,  'Косметология', 1466, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1471,  'Ателье', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1472,  'Ветеринарные услуги', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1473,  'Дезинфекция, дератация, дезинсекция', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1474,  'Доставка товаров, еды, цветов', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1475,  'Изготовление и ремонт мебели', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1476,  'Изготовление ключей, ремонт замков, заточка инструмента', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1477,  'Клининговые услуги', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1478,  'Коммунальные службы', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1479,  'Ремонт бытовой, аудио-, видеотехники', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1480,  'Прачечные и химчистки', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1481,  'Ритуальные услуги', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1482,  'Справочно-информационные услуги', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1483,  'Утилизация, вывоз, переработка отходов', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1484,  'Часовые мастерские', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1485,  'Ювелирные мастерские', 1470, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1486,  'Фото-видеосъемка', 1470, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6230,  'авто -эмали/аэрография', 1230, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6232,  'авто -чехлы/ковры', 1230, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6234,  'авто -стекла/зеркала', 1230, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1236,  'Авто -мото химия', 1229, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6242,  'для легковых автомобилей', 1231, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6243,  'для грузовых автомобилей', 1231, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6244,  'отечественные автомобили', 6242, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6245,  'иномарки', 6242, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6246,  'отечественные автомобили', 6243, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6247,  'иномарки', 6243, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6248,  'для общественного транспорта', 1231, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6249,  'для сельхозтехники', 1231, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6250,  'для мототехники', 1231, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6251,  'для спецтехники', 1231, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6252,  'автосигнализации', 1238, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6253,  'электрооборудование', 1238, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6254,  'звуковое оборудование', 1238, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6255,  'автокондиционеры', 1238, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6256,  'бухгалтерские системы', 1243, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6257,  'поисковые интернет-системы', 1243, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6258,  'системы мониторинга транспорта', 1243, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6259,  'информационные программы', 1243, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6260,  'мобильные телефоны', 1241, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6261,  'стационарные телефоны', 1241, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6262,  'мобильные аксессуары', 6260, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6263,  'мобильные запчасти', 6260, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6264,  'оборудование', 6261, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6265,  'запчасти', 6261, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6266,  'Антенное оборудование', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6267,  'Навигационное оборудование', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6268,  'Офисные АТС', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6269,  'Пейджинговое оборудование/системы', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6270,  'Платежное оборудование/системы', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6271,  'Спутниковая связь/оборудование', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6272,  'Кабельное телевидение/оборудование', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6273,  'Коммутационное оборудование', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6274,  'Электросвязь/оборудование', 1239, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1452,  'Туристические агентства, турооператоры', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6275,  'препараты/лекарства', 1249, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6276,  'медицинский инвентарь/инструмент/оборудование', 1249, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6277,  'парфюмерия', 1250, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6278,  'косметические товары', 1250, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6279,  'оборудование/ инвентарь по уходу за здоровьем/ красотой', 1250, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6280,  'средства гигиены', 1250, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6281,  'очки/контактные линзы', 1251, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6282,  'солнцезащитные очки', 1251, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6283,  'аксессуары', 1251, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6284,  'КРС', 1310, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6285,  'МРС', 1310, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6286,  'птица', 1310, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6289,  'Вторичные отделочные материалы', 1262, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6290,  'Автоматические ворота/ двери', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6291,  'Асбестотехническая продукция', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6292,  'Бетон/ раствор / цемент', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6293,  'Герметики/ Клеи', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6294,  'Гидроизоляционные материалы', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6295,  'Гипсокартон/комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6296,  'Грязепоглощающие покрытия', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6297,  'Декоративные элементы/ покрытия', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6298,  'ДСП / ДВП / Фанера', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6299,  'Железобетонные изделия', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6300,  'Звукоизоляционные материалы', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6301,  'Металлоконструкции / комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6302,  'Огнезащитные/ огнеупорные материалы', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6303,  'Пиломатериалы/ лесоматериалы', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6304,  'Теплоизоляционные материалы', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6305,  'Лакокрасочные материалы', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6306,  'Погонажные изделия', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6307,  'Светопрозрачные конструкции', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6308,  'Фасадные материалы / конструкции', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6309,  'Кровельные материалы', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6310,  'Крепёжные изделия/ конструкции', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6311,  'Керамическая плитка / кафель / тротуарная плитка / керамогранит', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6312,  'Входные / межкомнатные двери / комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6313,  'Окна / комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6314,  'Заборы/ ограждения', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6315,  'Замки / скобяные изделия / комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6316,  'Материалы для витражей / мозаики', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6317,  'Напольные покрытия/ комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6318,  'Стекло / зеркала', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6319,  'Оргстекло / поликарбонат', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6320,  'Резиновые покрытия / комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6321,  'Стеновые панели / Сэндвич-панели', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6322,  'Строительные смеси', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6323,  'Стекломагнезитовые материалы / комплектующие', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6324,  'Потолки', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6325,  'Обои', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6326,  'Кирпич', 1263, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6329,  'Щебень', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6330,  'Песок', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6331,  'ПГС / ЩПС', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6332,  'Керамзит', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6333,  'Гравий', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6334,  'Грунт', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6335,  'Асфальтная крошка', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6336,  'Бой кирпича / бой бетона', 6289, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6337,  'Системы сигнализации', 1306, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6338,  'Домофоны', 1306, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6339,  'Огнезащитные системы', 1304, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6340,  'Пломбировочные устройства', 1304, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6341,  'Детекторы лжи', 1303, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6342,  'Промышленная химия', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6343,  'Пластмассовые изделия', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6344,  'Сорбенты', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6345,  'Технические газы/Криогенные жидкости', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6346,  'Уголь', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6347,  'Вторсырьё', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6348,  'Металлопрокат', 1253, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6349,  'черный', 6348, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6350,  'цветной', 6348, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6351,  'нержавеющий', 6348, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6327,  'натяжные', 6324, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6328,  'навесные', 6324, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6352,  'Пакеты / Пленки', 1265, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6353,  'Техника для искусства', 1244, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6354,  'кухонная техника / аксессуары', 1245, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6355,  'климатическая техника / аксессуары', 1245, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6356,  'гладильное/швейное оборудование', 1245, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6357,  'техника для дома / аксессуары', 1245, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6358,  'компьютеры/ комплектующие', 1246, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6359,  'печатное оборудование / комплектующие', 1246, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6360,  'телефонное оборудование', 1246, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6362,  'аудио-видео техника', 1247, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6363,  'фото – техника', 1247, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6364,  'музыкальные инструменты / аксессуары', 6353, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6365,  'художественное оборудование / комплектующие', 6353, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6366,  'театральные, кино товары / атрибутика', 6353, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6367,  'для ванной комнаты', 1285, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6368,  'для кухни', 1285, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6369,  'для офиса', 1285, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6370,  'для садово-парковой зоны', 1285, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6371,  'Мебельная фурнитура', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6372,  'Мебельные ткани', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6373,  'Мебельные фасады', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6374,  'Матрацы', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6375,  'Изделия из декоративного камня', 1284, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6376,  'Карнизы', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6377,  'Кованые изделия', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6378,  'Швейная фурнитура', 1320, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6379,  'Декор', 1320, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6381,  'Спортивный инвентарь / техника', 6380, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6382,  'Спортивная одежда /Обувь /Аксессуары /Атрибутика', 6380, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6383,  'Спортивно-наградная продукция', 6380, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6384,  'Спортивно- развлекательное оборудование', 6380, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6385,  'Спортивное питание', 6380, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6386,  'Товары для туризма/рыбалки/охоты', 6380, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6387,  'снаряжения для туризма и отдыха', 6386, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6389,  'Ветеринарные аптеки', 6388, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6390,  'Ветеринарные клиники', 6388, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6391,  'Ветеринарные лаборатории', 6388, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6392,  'Зоотовары', 6388, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6393,  'препараты', 6389, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6394,  'средства по уходу', 6389, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6396,  'Геодезическое оборудование', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6397,  'Кабель /Провод', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6398,  'Контрольно-измерительные приборы', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6399,  'Оборудование радиационного контроля', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6400,  'Опоры линий электропередач', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6401,  'Оптические приборы', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6402,  'Радиоэлектронные приборы', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6403,  'Светотехника', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6404,  'Судовое электрооборудование', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6405,  'Электродвигатели/Редукторы', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6406,  'Электроизоляционные материалы', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6407,  'Электронагревательное оборудование', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6408,  'Электронные компоненты', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6409,  'Электронное табло', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6410,  'Электротехническая продукция', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6411,  'Электроустановочная продукция', 6395, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6412,  'Элементы/приборы питания', 6395, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6414,  'Материалы для наружной/ световой/Indoor рекламы', 6413, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6415,  'Голографическая продукция', 6413, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6416,  'Полиграфия', 6413, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6417,  'Производство пластиковых карт/Контрольных браслетов', 6413, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6418,  'Фотокниги/Бизнес-сувениры/Фотобанки', 6413, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6419,  'Товары для полиграфии/Оборудование /Инструмент', 6413, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6420,  'Телеканалы/Радиостанции/Интернет', 6413, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6422,  'Детское питание', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6423,  'Диетические/Соевые продукты', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6424,  'Маслопродукты', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6425,  'Зерно/Зернопереработка/Зерноотходы', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6426,  'Готовая продукция/Продукты быстрого приготовления', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6427,  'Кондитерские изделия', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6428,  'Колбасные изделия/Сыры', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6429,  'Консервированная продукция', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6430,  'Макаронные изделия', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6437,  'Продукты пчеловодства', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6438,  'Овощи/Фрукты /Орехи/Семечки', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6439,  'Сахар /Соль /Специи /Пряности', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6440,  'Снэковая продукция', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6451,  'Головные/Шейные уборы', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6452,  'Нижнее белье', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6453,  'Аксессуары', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6458,  'Для беременных', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6459,  'Детская одежда', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6460,  'Детская обувь', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6462,  'Школьная форма', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6463,  'Сценическая/Карнавальная одежда/Обувь', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6464,  'Мужская одежда', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6471,  'Абразивоструйное оборудование/ Абразивный инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6472,  'Банковское оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6473,  'Бензиновое/дизельное оборудование / Бензоинструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6474,  'Буровое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6478,  'Газовое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6479,  'Гидравлическое оборудование / Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6488,  'Окрасочное оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6489,  'Очистительное оборудование / Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6490,  'Полиграфическое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6497,  'Стеклообрабатывающее оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6498,  'Электроинструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6499,  'Резинотехническое оборудование / Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6500,  'Пневматическое/компрессорное оборудование / Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6501,  'Насосное оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6502,  'Металлообрабатывающее оборудование/ Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6503,  'Малярный инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6504,  'Клининговое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6505,  'Слесарно-монтажный инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6431,  'Мелкофасованные продукты питания', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6432,  'Молочные продукты', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6433,  'Мука/крупы', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6436,  'Рыба/Морепродукты', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6435,  'Мясо птицы /Полуфабрикаты', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6434,  'Мясо /Полуфабрикаты', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6441,  'Хлебобулочные изделия', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6442,  'Фаст-фудная продукция', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6443,  'Ягоды / Грибы', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6444,  'Яичная продукция', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6445,  'Алкогольные напитки', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6446,  'Безалкогольные напитки', 6421, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6447,  'Табачные изделия /Товары для курения', 6421, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6449,  'Женская одежда', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6450,  'Верхняя одежда', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6454,  'Бижутерия', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6455,  'Обувь /Аксессуары для обуви', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6456,  'Меха/Дублёнки/Кожа', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6457,  'Чулочно-носочные изделия', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6461,  'Для новорождённых', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6465,  'Секонд-хенд', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6466,  'Свадебная одежда/Обувь', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6467,  'Спецодежда/Спецобувь', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6468,  'Сумки/Кожгалантерея', 6448, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6469,  'Трикотажные изделия', 6448, 1227);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6475,  'Вендинговое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6476,  'Вентиляционное/Тепловое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6477,  'Весовое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6480,  'Горно-шахтовое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6481,  'Деревообрабатывающее оборудование/ Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6482,  'Звуковое/световое/видеооборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6483,  'Игорное оборудование/ Аксессуары', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6484,  'Кинооборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6485,  'Котельное оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6486,  'Лингафонное оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6487,  'Нефтегазовое оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6491,  'Проекционное оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6492,  'Сварочное оборудование / Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6493,  'Холодильное оборудование', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6494,  'Швейное оборудование / инструмент/ аксессуары', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6495,  'Ткацкое оборудование /инструмент / аксессуары', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6496,  'Строительное оборудование /Инструмент', 6470, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6507,  'Детективные услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6508,  'Ипотечное/Жилищное кредитование', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6509,  'Кредитные кооперативы', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6510,  'Лицензии, допуски СРО помощь в оформлении', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6511,  'Ломбарды', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6512,  'Миграционные услуги', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6513,  'Микрофинансовые организации', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6514,  'Ведение реестра акционеров', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6515,  'Социологические исследования', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6516,  'Услуги переводчиков', 1344, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6517,  'печатная продукция', 6416, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6518,  'газеты/журналы/справочники', 6517, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6519,  'рекламная продукция', 6416, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6520,  'POS – материалы (буклеты, листовки и т.п.)', 6519, 1227);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1403,  'Газеты, журналы иные периодические издания', 1402, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6521,  'аромомаркетинг', 1404, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6522,  'маркетинговые/социологические исследования', 1404, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6523,  'организация и проведение мероприятий', 1404, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6524,  'офсетная печать', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6525,  'тампопечать', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6526,  'термопечать', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6527,  'УФ-печать', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6528,  'флексопечать', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6529,  'шелкография', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6530,  'широкоформатная печать', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6532,  'оперативная полиграфия', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6533,  'печать на предметах интерьера/текстиле/одежде', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6531,  'предпечатная подготовка/послепечатная обработк', 1410, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6534,  'Услуги БТИ', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6535,  'Продажа земельных участков', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6536,  'Продажа жилой недвижимости', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6537,  'Продажа нежилой недвижимости', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6538,  'Межевание земель', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6539,  'Кадастровый учет', 1396, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6556,  'Центры массажа', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6557,  'Центры снижения веса', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6558,  'Музыкальные школы/студии', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6559,  'Модельные школы', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6560,  'Университеты/институты', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6540,  'Услуги строительной техники', 1414, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6541,  'Автовокзалы', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6542,  'Аэропорты', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6543,  'Ж/д вокзалы', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6545,  'Мобильная связь', 1365, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6546,  'Спутниковая связь', 1365, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6547,  'IP-телефония', 1365, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6548,  'Ремонт средств связи', 1371, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6561,  'Училища/техникумы/колледжи', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6562,  'Художественные школы', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6563,  'Фотошколы', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6564,  'Центры иностранных языков', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6565,  'Школы/гимназии/лицеи/школы-интернаты', 1380, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6544,  'Услуги погрузки', 1431, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6549,  'Пластическая хирургия', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6550,  'Реабилитационные центры', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6551,  'Родильные дома', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6553,  'Станции переливания крови', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6554,  'Травмпункты', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6555,  'Хоспис', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6552,  'Санатории/профилактории', 1376, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6566,  'Боди-арт', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6567,  'Диетологи', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6568,  'Наращивание волос', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6569,  'Ногтевые центры/студии', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6570,  'Парикмахерские', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6571,  'Студии загара', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6572,  'Тату-салоны', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6573,  'Тонизирующие салоны', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6574,  'Тренажерные залы', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6575,  'Услуги визажиста', 1466, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6576,  'Фитнес-клубы', 1466, 1342);

INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6577,  'Аквапарки/водные аттракционы', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6578,  'Активные туры', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6579,  'Бани/сауны', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6580,  'Дайвинг-центры', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6581,  'Интернет-кафе', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6582,  'Кулинарные шоу/мастер классы', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6583,  'Пляжи', 1443, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6584,  'Вневедомственная охрана', 1387, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6585,  'Проектирование охранно-пожарных систем', 1387, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6586,  'Профилактика пожаров', 1387, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6587,  'Аэрография на транспорте', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6588,  'Автозаправочные станции', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6589,  'Автостоянки/паркинги', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6590,  'Авторазбор', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6591,  'Авточехлы пошив/ремонт', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6592,  'Замена масла', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6593,  'Компьютерная диагностика автомобилей', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6594,  'Кузовной ремонт', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6595,  'Ремонт спецтехники', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6596,  'Техосмотр', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6597,  'Тонировка/шумоизоляция', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6598,  'Тюнинг центры', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6599,  'Хранение шин', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6600,  'Шиномонтаж', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (6601,  'Эвакуатор/мобильная техпомощь', 1391, 1342);
INSERT INTO public.category (id,  name, parent_id, categorytype_id) VALUES (1235,  'Шины|Диски', 1229, 1227);