<?php
/**
 * Created by PhpStorm.
 * User: marvel
 * Date: 15.09.17
 * Time: 15:15
 */

namespace common\models;


use yii\db\ActiveRecord;

class PaymentSystem extends ActiveRecord
{
    public static function tableName()
    {
        return 'payment_system'; // TODO: Change the autogenerated stub
    }
}