<?php
/**
 * Created by PhpStorm.
 * User: marvel
 * Date: 20.09.17
 * Time: 22:11
 */

namespace frontend\models;


use common\models\PaymentRequest;
use common\models\Tariffs;
use DateInterval;
use DateTime;
use Yii;
use yii\base\Model;

class BillingForm extends Model
{

    const INCOME = 1;
    const LOGIN = 'deloved.info@gmail.com';
    const PASS = 'Delo2016ved';
    const SITE = 'https://paymaster.ru';
    const PATH = '/partners/rest/getPaymentByInvoiceID';
    const MERCHANT_ID = 'a2498ef4-9f7c-4bc0-ad34-edacc30ffc6b';





    public $tariff;
    public $method;
    public $account;
    public $keeper;

    public function rules()
    {
        return [
            [['tariff','method'],'integer'],
            [['tariff','method'],'required']
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'method'=>\Yii::t('app','Method'),
            'tariff'=>\Yii::t('app','Tariff'),
        ];
    }


    public function getIncome(){
        $session = Yii::$app->session;
        $timeZone = $session->get('timeZone')/60;
        $paymentReq = new PaymentRequest();
        $paymentReq->keeper_id = $this->keeper;
        $paymentReq->account_id = $this->account;
        $paymentReq->date_created = (new DateTime(date('Y-m-d H:i:s')))->add(new DateInterval('PT'.$timeZone.'H'))->format('Y-m-d H:i:s');
        $paymentReq->method_id = $this->method;
        $paymentReq->value = $this->tariff;
        $paymentReq->status = PaymentRequest::STATUS_INITIATED;
        $paymentReq->save();
        return $paymentReq;
    }





}